name: C4GT Ticket Beta
description: Create a new Ticket for C4GT Community
title: "[C4GT Community]: "
labels: ["C4GT Community"]
body:
  - type: textarea
    id: ticket-description
    attributes:
      description: Provide a brief description of the feature, including why it is needed and what it will accomplish.
      label: Ticket Contents
      value: |
        ## Description
        [Provide a brief description of the feature, including why it is needed and what it will accomplish. You can skip any of Goals, Expected Outcome, Implementation Details, Mockups / Wireframes if they are irrelevant. Please note that this section of the ticket is suggestive & you can structure it as per your prerogative.]

        ## Goals
        - [ ] [Goal 1]
        - [ ] [Goal 2]
        - [ ] [Goal 3]
        - [ ] [Goal 4]
        - [ ] [Goal 5]

        ## Expected Outcome
        [Describe in detail what the final product or result should look like and how it should behave.]
        
        ## Acceptance Criteria
        - [ ] [Criteria 1]
        - [ ] [Criteria 2]
        - [ ] [Criteria 3]
        - [ ] [Criteria 4]
        - [ ] [Criteria 5]
        
        ## Implementation Details
        [List any technical details about the proposed implementation, including any specific technologies that will be used.]
        
        ## Mockups / Wireframes
        [Include links to any visual aids, mockups, wireframes, or diagrams that help illustrate what the final product should look like. This is not always necessary, but can be very helpful in many cases.]   - type: input 
  - type: input
    id: ticket-project
    attributes:
      label: Project Name
      placeholder: Enter project name
  - type: dropdown
    id: ticket-category
    attributes: 
      label: Category
      description: Choose the categories that best describe your ticket
      multiple: true
      options:
        - CI/CD
        - Integrations
        - Performance Improvement
        - Security
        - UI/UX/Design
        - Bug
        - Feature
        - Documentation
        - Deployment
        - Test
        - PoC
        - Other
      
