name: C4GT Ticket
description: Create a new Ticket for C4GT Community
title: "[C4GT Community]: "
labels: ["C4GT Community"]
body:
  - type: textarea
    id: ticket-description
    attributes:
      description: Provide a brief description of the feature, including why it is needed and what it will accomplish.
      label: Description
      placeholder: Please enter a complete description of the ticket
